config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'

# ルートドメインからwwwカスタムドメインへのリダイレクト
constraints(host: /^my-memoria\.com$/) do
  match '(*any)' => redirect { |params, req| "https://www.my-memoria.com/#{params[:any]}" }, via: :all
end

  resources :articles do
    resource :like, only: [:create, :destroy]
    resources :comments, only: [:index,:show, :create, :destroy]
  end
  
  resource :profile, only: [:show, :edit, :update]
  
  resources :accounts, only: [:show] do
    resources :follows, only:[:create]
    resources :unfollows, only:[:create]
    resources :followers, only: [:index]
    resources :followings, only: [:index]
  end

  resources :search, only: [:index]

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validate :validate_images_count

  scope :in_last_24_hours, -> { where('articles.created_at > ?', 24.hours.ago) }#人気記事の表示スコープ
  scope :popular, -> { 
    joins(:likes)
    .select('articles.*, COUNT(likes.id) AS likes_count')
    .group('articles.id')
    .order('likes_count DESC')
  }

    scope :search_by_text, ->(query) { where("text LIKE ?", "%#{query}%") } #記事のテキスト検索スコープ
    scope :search_by_username, -> (query) { joins(:user).where("users.name LIKE ?", "%#{query}%") }#記事のユーザー検索スコープ
  
  private

  def validate_images_count
    if images.count == 0
      errors.add(:base, "少なくとも1枚の画像が必要です")
    elsif images.count > 3
      errors.add(:base, "一度に送信できる画像は3枚までです")
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_profile

    def index
        # フォローしているユーザーと自分自身の投稿を取得
        following_and_own_articles = Article.where(user_id: current_user.following.pluck(:id) << current_user.id).order(created_at: :desc)
        
        # 24時間以内に作成され、いいねが多い投稿を5件取得
        popular_articles = Article.popular.limit(5)
    
        # 両方の記事リストを結合し、重複を削除して新しい順にソート
        @articles = (following_and_own_articles + popular_articles).uniq.sort_by { |article| article[:created_at] }.reverse
    end
    
    def show
        @article = Article.find(params[:id])
        @comments = @article.comments.order(created_at: :desc)
        @comment = @article.comments.new
    end


    def new
        @article = Article.new
    end

    def create
        @article = current_user.articles.build(article_params)
    
        if @article.save
            redirect_to root_path, notice: '記事を投稿しました。'
        else
            flash.now[:alert] = '記事の投稿に失敗しました。'
            render :new
        end
    end
    
    def destroy
        @article = Article.find(params[:id])
        if @article.user == current_user
            @article.likes.destroy_all # 記事に関連するいいねをすべて削除
            @article.destroy!
            redirect_to articles_url, notice: '記事が削除されました。'
        else
            redirect_to articles_path, alert: 'この記事を削除する権限がありません。'
        end
    end

    private

    def article_params
        params.require(:article).permit(:content, images: [])
    end

	def set_profile
        @profile = current_user.profile
    end

end

app/views/articles/index.html.haml
.timeline-page
	= link_to image_tag('photo-camera.png', alt: '投稿', class: 'post-btn custom-img'), new_article_path
	= link_to image_tag('search.png', alt: '検索', class: 'search-btn custom-img'), search_index_path

	%ul.article-list
		- @articles.each do |article|
			= render 'common/article', article: article

app/views/articles/new.html.haml
= form_with(model: @article, local: true) do |f|
  - if @article.errors.any?
    - @article.errors.full_messages.each do |message|
      %p= message

  .article-new-header
    = link_to 'Back', :back, class: 'btn article-new-cancel custom-link'
    .article-new-status New Post
    = f.submit 'Post', class: ' btn article-new-post'
  
  .article-new-profile
    = image_tag(@profile.avatar.presence || 'default-avatar.png', class: 'article-new-avatar')
    %span.article-new-username= @profile.user.display_name.present? ? @profile.user.display_name : @profile.user.username

  .article-new-textarea
    = f.text_area :content, class: 'article-new-input', placeholder: "What's on your mind?"

  .article-new-upload
    = f.label :images, ' + Album', class: 'article-new-label'
    = f.file_field :images, multiple: true, accept: "image/*", class: 'article-new-file-input'
    .article-new-preview

app/views/articles/show.html.haml
.container
  = link_to 'Back', :back, class: 'btn btn-default'
  .comments{ data: { article_id: @article.id } }

  .new_comment{ data: { article_id: @article.id } }
    = form_with model: [@article, @comment], local: true, html: { id: 'comment_form' } do |f|
      = f.text_area :content, placeholder: "コメントを入力..."
      = f.submit "コメントを投稿", class: 'button', data: { disable_with: false }


  = button_tag "コメントする", type: "button", id: "show_comment_form_btn"