config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'

# ルートドメインからwwwカスタムドメインへのリダイレクト
constraints(host: /^my-memoria\.com$/) do
  match '(*any)' => redirect { |params, req| "https://www.my-memoria.com/#{params[:any]}" }, via: :all
end

  resources :articles do
    resource :like, only: [:create, :destroy]
    resources :comments, only: [:index,:show, :create, :destroy]
  end
  
  resource :profile, only: [:show, :edit, :update]
  
  resources :accounts, only: [:show] do
    resources :follows, only:[:create]
    resources :unfollows, only:[:create]
    resources :followers, only: [:index]
    resources :followings, only: [:index]
  end

  resources :search, only: [:index]

end

app/views/common/_article.html.haml
%li.article-item
    .user-info
        .user-details
            - if current_user == article.user
                = link_to profile_path(id: article.user.id) do
                    = image_tag(article.user.profile.avatar.presence || 'default-avatar.png', class: 'user-image')
                %span.user-name= article.user.display_name.present? ? article.user.display_name : article.user.username
            - else
                = link_to account_path(id: article.user.id) do
                    = image_tag(article.user.profile.avatar.presence || 'default-avatar.png', class: 'user-image')
                %span.user-name= article.user.display_name.present? ? article.user.display_name : article.user.username
        - if current_user == article.user
            = link_to article_path(article), method: :delete, data: { confirm: '記事を削除してよろしいですか？' } do
                = image_tag('trash.png', alt: '削除', class: 'delete-article-button')


    %span.post-time
        = time_ago_in_words(article.created_at)


    .article-image-container
        - case article.images.count
        - when 0
            = image_tag 'default-image.png', class: 'single-image article-image', alt: 'デフォルト画像', data: { target: 'default-image.png' }
        - when 1
            = image_tag article.images.first, class: 'single-image article-image', data: { target: rails_blob_path(article.images.first, only_path: true) }
        - when 2
            = image_tag article.images.first, class: 'main-image article-image', data: { target: rails_blob_path(article.images.first, only_path: true) }
            = image_tag article.images.second, class: 'double-image article-image', data: { target: rails_blob_path(article.images.second, only_path: true) }
        - else
            = image_tag article.images.first, class: 'main-image article-image', data: { target: rails_blob_path(article.images.first, only_path: true) }
            .side-images
                - article.images[1..2].each do |image|
                    = image_tag image, class: 'side-image article-image', data: { target: rails_blob_path(image, only_path: true) }

    .modal
        .modal-content
            %img{src: "", alt: "モーダル画像", class: "modal-image"}
            %button.close{class: "modal-btn"} &times;
            %button.left-arrow{class: "modal-btn"} &lt;
            %button.right-arrow{class: "modal-btn"} &gt;


    .article-actions
        .like-icons{ 'data-article-id': article.id, 'data-is-liked': current_user.has_liked?(article) }
            = image_tag('like.png', alt: 'いいね', class: 'like-button-inactive', style: ('display: none;' if current_user.has_liked?(article)))
            = image_tag('like_red.png', alt: 'いいね済み', class: 'like-button-active', style: ('display: block;' if current_user.has_liked?(article)))
        = link_to image_tag('comment.png', alt: 'コメント', class: 'comment-button'), article_comments_path(article)
        - if article && article.content
            - x_share_url = "https://x.com/share?url=#{CGI.escape(article_url(article))}&text=#{CGI.escape(article.content)}"
        = link_to image_tag('share.png', alt: 'シェア', class: 'share-button'), x_share_url, target: "_blank"

    .article-text
        = article.content

app/views/common/_profile.html.haml
.profile-header
  = link_to 'Back', :back, class: 'custom-link'
  - unless current_user == @user
    %button.follow-btn{ data: { user_id: @user.id, relationship_status: current_user.following?(@user) ? 'unfollow' : 'follow' } }
      = current_user.following?(@user) ? 'Unfollow' : 'Follow'
.profile-info
  %p= @user.display_name.present? ? @user.display_name : @user.username

= image_tag(@user.profile.avatar.presence || 'default-avatar.png', class: 'profile-avatar')

%input#avatarInput{ type: "file", name: "avatar" }

.profile-stats
  .stat-item
    %div= @user.articles.count
    %p Posts
  .stat-item
    = link_to account_followers_path(@user), class: 'follower-link custom-link' do
      %div#follower-count= @user.follower.count
      %p Followers
  .stat-item
    = link_to account_followings_path(@user), class: 'following-link custom-link' do
      %div= @user.following.count
      %p Following

.posts-timeline
  - @user.articles.order(created_at: :desc).each do |article|
    .article-image-container
      - case article.images.count
      - when 1
        = image_tag article.images.first, class: 'single-image article-image', data: { target: rails_blob_path(article.images.first, only_path: true) }
      - when 2
        = image_tag article.images.first, class: 'main-image article-image', data: { target: rails_blob_path(article.images.first, only_path: true) }
        = image_tag article.images.second, class: 'double-image article-image', data: { target: rails_blob_path(article.images.second, only_path: true) }
      - else
        = image_tag article.images.first, class: 'main-image article-image', data: { target: rails_blob_path(article.images.first, only_path: true) }
        .side-images
          - article.images[1..2].each do |image|
            = image_tag image, class: 'side-image article-image', data: { target: rails_blob_path(image, only_path: true) }


.modal
  .modal-content
    %img{src: "", alt: "モーダル画像", class: "modal-image"}
    %button.close{class: "modal-btn"} &times;
    %button.left-arrow{class: "modal-btn"} &lt;
    %button.right-arrow{class: "modal-btn"} &gt;

app/views/common/_user_list.html.haml
%ul.user-list
  - users&.each do |user|
    %li.user-item
      = link_to account_path(id: user.id), class: 'user-link custom-link' do
        = image_tag(user.profile.avatar.presence || 'default-avatar.png', class: 'user-avatar')
        .user-info
          %span.user-name= user.display_name.present? ? user.display_name : user.username
          - if user.last_active_at && user.last_active_at > 5.minutes.ago
            %span.user-last-login オンライン
          - else
            %span.user-last-login= time_ago_in_words(user.last_active_at)